version: 2.1

orbs:
  python: circleci/python@2.0.3

commands:
  send_report:
    description: Download Codacy's coverage reporter and run it
    parameters:
      coverage-reports:
        default: ""
        description: Optional comma separated list of coverage reports to send to Codacy
        type: string
      project-token:
        default: ${CODACY_PROJECT_TOKEN}
        description: Specify Codacy's project token
        type: string
      skip:
        default: false
        description: Skip if token isn't defined. Useful to let forks CI pass without passing secrets
        type: boolean
      tool_version:
        default: ""
        description: Specify Codacy's coverage reporter tool version
        type: string
    steps:
      - run:
          command: |
            export CODACY_REPORTER_VERSION=<< parameters.tool_version >>
            export CODACY_PROJECT_TOKEN=<< parameters.project-token >>
            report_array=$(printf "<< parameters.coverage-reports >>" | cut -d',' -f1)

            params=''
            for report in $report_array
            do
                if [ ! -z "$report" ]
                then
                    params="$params -r $report"
                fi
            done

            if << parameters.skip >>; then
                skip_option="--skip"
            else
                skip_option=""
            fi


            if [ -x "$(which curl)" ]; then
                curl -Ls https://coverage.codacy.com/get.sh > get.sh
            elif [ -x "$(which wget)" ] ; then
                wget -qO - https://coverage.codacy.com/get.sh > get.sh
            else
                printf "Could not find curl or wget, please install one."
            fi

            source get.sh report $params --partial $skip_option &&\
            source get.sh final $skip_option
          name: Upload Coverage Results to Codacy

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.10.2
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
          # app-dir: ~/project/package-directory/  # If you're requirements.txt isn't in the root directory.
          # pip-dependency-file: test-requirements.txt  # if you have a different name for your requirements file, maybe one that combines your runtime and test requirements.
      - run:
          name: Run Tests
          command: |
            coverage run -m pytest
            coverage report
            coverage xml
            ls
      - run:
          name: Collect test results
          command: |
            mkdir -p ~/workdir/codacy/
            cp coverage.xml ~/workdir/codacy/
          when: always
      - store_artifacts:
          path: coverage.xml
      - persist_to_workspace:
          root: ~/workdir
          paths:
            - codacy
  ma-coverage:
    description: Runs codacy analysis on jacoco reports and uploads them to codacy using given project token
    parameters:
      codacy_project_token:
        type: string
        description: Codacy Project token taken from codacy
      cache-version:
        type: string
        description: Cache version; increment this for a fresh cache.
        default: "v1"
    docker:
      - image: 'circleci/openjdk:8-jdk'
    working_directory: ~/workdir/codacy
    environment:
      CODACY_JAR_URL: https://api.github.com/repos/codacy/codacy-coverage-reporter/releases/latest
      CODACY_JAR_PATH: codacy-coverage-reporter.jar
      CODACY_PROJECT_TOKEN: << parameters.codacy_project_token>>
    steps:
      - restore_cache:
          name: Restore npm cache
          keys:
            - ma-coverage-<< parameters.cache-version >>-{{ .Branch }}
            - ma-coverage-<< parameters.cache-version >>
      - run:
          name: Setup
          command: |
            export PATH="node_modules/.bin:$PATH"
            npm i fx
            DOWNLOAD_URL=$(curl -s "$CODACY_JAR_URL" | fx 'this.assets[0].browser_download_url')
            curl -L -o "$CODACY_JAR_PATH" "$DOWNLOAD_URL"
            echo "java -jar '$PWD/$CODACY_JAR_PATH' \$@" > codacy.sh
            chmod +x codacy.sh
      - save_cache:
          name: Store npm cache
          key: ma-coverage-<< parameters.cache-version >>-{{ .Branch }}
          paths: [ node_modules ]
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Upload to Codacy
          command: |
            find . -type f -regex "coverage.xml" -exec echo {} \; -exec ./codacy.sh report -l Java -r {} --partial \;
            ./codacy.sh final
            rm codacy.sh
  coverage:
    docker:
      - image: 'circleci/openjdk:8-jdk'
    working_directory: ~/workdir/codacy
    steps:
      - checkout
      - attach_workspace:
          at: ~/workdir
      - run:
          name: Check files in workspace
          command: |
            pwd
            ls
      - send_report:
          coverage-reports: 'coverage.xml'
          project-token: $CODACY_PROJECT_TOKEN

workflows:
  main:
    jobs:
      - build-and-test
      - ma-coverage:
          codacy_project_token: $CODACY_PROJECT_TOKEN
          requires:
            - build-and-test
          filters:
            branches:
              only: master
